// action types
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PHRASES = 'SET_PHRASES';
export const SET_LANGUAGE_NAME = 'SET_LANGUAGE_NAME';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_THEME = 'SET_THEME';
export const SET_NEW_PHRASES = 'SET_NEW_PHRASES';
export const SET_LEARNT_PHRASES = 'SET_LEARNT_PHRASES';
export const SET_SEEN_PHRASES = 'SET_SEEN_PHRASES';
